HTTP_CREATED = 201
HTTP_ACCEPTED = 202
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_NOT_IMPLEMENTED = 501

DATABASE_NAME = "hayden"

CONTACT_EMAIL_ADDRESS = "contact@pingu.com"

